// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Axenos-dev/sse-openai-server/ent/chatdb"
	"github.com/Axenos-dev/sse-openai-server/ent/predicate"
)

// ChatDBQuery is the builder for querying ChatDB entities.
type ChatDBQuery struct {
	config
	ctx        *QueryContext
	order      []chatdb.OrderOption
	inters     []Interceptor
	predicates []predicate.ChatDB
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ChatDBQuery builder.
func (cdq *ChatDBQuery) Where(ps ...predicate.ChatDB) *ChatDBQuery {
	cdq.predicates = append(cdq.predicates, ps...)
	return cdq
}

// Limit the number of records to be returned by this query.
func (cdq *ChatDBQuery) Limit(limit int) *ChatDBQuery {
	cdq.ctx.Limit = &limit
	return cdq
}

// Offset to start from.
func (cdq *ChatDBQuery) Offset(offset int) *ChatDBQuery {
	cdq.ctx.Offset = &offset
	return cdq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (cdq *ChatDBQuery) Unique(unique bool) *ChatDBQuery {
	cdq.ctx.Unique = &unique
	return cdq
}

// Order specifies how the records should be ordered.
func (cdq *ChatDBQuery) Order(o ...chatdb.OrderOption) *ChatDBQuery {
	cdq.order = append(cdq.order, o...)
	return cdq
}

// First returns the first ChatDB entity from the query.
// Returns a *NotFoundError when no ChatDB was found.
func (cdq *ChatDBQuery) First(ctx context.Context) (*ChatDB, error) {
	nodes, err := cdq.Limit(1).All(setContextOp(ctx, cdq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{chatdb.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (cdq *ChatDBQuery) FirstX(ctx context.Context) *ChatDB {
	node, err := cdq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ChatDB ID from the query.
// Returns a *NotFoundError when no ChatDB ID was found.
func (cdq *ChatDBQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = cdq.Limit(1).IDs(setContextOp(ctx, cdq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{chatdb.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (cdq *ChatDBQuery) FirstIDX(ctx context.Context) int {
	id, err := cdq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ChatDB entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ChatDB entity is found.
// Returns a *NotFoundError when no ChatDB entities are found.
func (cdq *ChatDBQuery) Only(ctx context.Context) (*ChatDB, error) {
	nodes, err := cdq.Limit(2).All(setContextOp(ctx, cdq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{chatdb.Label}
	default:
		return nil, &NotSingularError{chatdb.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (cdq *ChatDBQuery) OnlyX(ctx context.Context) *ChatDB {
	node, err := cdq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ChatDB ID in the query.
// Returns a *NotSingularError when more than one ChatDB ID is found.
// Returns a *NotFoundError when no entities are found.
func (cdq *ChatDBQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = cdq.Limit(2).IDs(setContextOp(ctx, cdq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{chatdb.Label}
	default:
		err = &NotSingularError{chatdb.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (cdq *ChatDBQuery) OnlyIDX(ctx context.Context) int {
	id, err := cdq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ChatDBs.
func (cdq *ChatDBQuery) All(ctx context.Context) ([]*ChatDB, error) {
	ctx = setContextOp(ctx, cdq.ctx, "All")
	if err := cdq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ChatDB, *ChatDBQuery]()
	return withInterceptors[[]*ChatDB](ctx, cdq, qr, cdq.inters)
}

// AllX is like All, but panics if an error occurs.
func (cdq *ChatDBQuery) AllX(ctx context.Context) []*ChatDB {
	nodes, err := cdq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ChatDB IDs.
func (cdq *ChatDBQuery) IDs(ctx context.Context) (ids []int, err error) {
	if cdq.ctx.Unique == nil && cdq.path != nil {
		cdq.Unique(true)
	}
	ctx = setContextOp(ctx, cdq.ctx, "IDs")
	if err = cdq.Select(chatdb.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (cdq *ChatDBQuery) IDsX(ctx context.Context) []int {
	ids, err := cdq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (cdq *ChatDBQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, cdq.ctx, "Count")
	if err := cdq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, cdq, querierCount[*ChatDBQuery](), cdq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (cdq *ChatDBQuery) CountX(ctx context.Context) int {
	count, err := cdq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (cdq *ChatDBQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, cdq.ctx, "Exist")
	switch _, err := cdq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (cdq *ChatDBQuery) ExistX(ctx context.Context) bool {
	exist, err := cdq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ChatDBQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (cdq *ChatDBQuery) Clone() *ChatDBQuery {
	if cdq == nil {
		return nil
	}
	return &ChatDBQuery{
		config:     cdq.config,
		ctx:        cdq.ctx.Clone(),
		order:      append([]chatdb.OrderOption{}, cdq.order...),
		inters:     append([]Interceptor{}, cdq.inters...),
		predicates: append([]predicate.ChatDB{}, cdq.predicates...),
		// clone intermediate query.
		sql:  cdq.sql.Clone(),
		path: cdq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Topic string `json:"topic,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ChatDB.Query().
//		GroupBy(chatdb.FieldTopic).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (cdq *ChatDBQuery) GroupBy(field string, fields ...string) *ChatDBGroupBy {
	cdq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ChatDBGroupBy{build: cdq}
	grbuild.flds = &cdq.ctx.Fields
	grbuild.label = chatdb.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Topic string `json:"topic,omitempty"`
//	}
//
//	client.ChatDB.Query().
//		Select(chatdb.FieldTopic).
//		Scan(ctx, &v)
func (cdq *ChatDBQuery) Select(fields ...string) *ChatDBSelect {
	cdq.ctx.Fields = append(cdq.ctx.Fields, fields...)
	sbuild := &ChatDBSelect{ChatDBQuery: cdq}
	sbuild.label = chatdb.Label
	sbuild.flds, sbuild.scan = &cdq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ChatDBSelect configured with the given aggregations.
func (cdq *ChatDBQuery) Aggregate(fns ...AggregateFunc) *ChatDBSelect {
	return cdq.Select().Aggregate(fns...)
}

func (cdq *ChatDBQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range cdq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, cdq); err != nil {
				return err
			}
		}
	}
	for _, f := range cdq.ctx.Fields {
		if !chatdb.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if cdq.path != nil {
		prev, err := cdq.path(ctx)
		if err != nil {
			return err
		}
		cdq.sql = prev
	}
	return nil
}

func (cdq *ChatDBQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ChatDB, error) {
	var (
		nodes = []*ChatDB{}
		_spec = cdq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ChatDB).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ChatDB{config: cdq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, cdq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (cdq *ChatDBQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := cdq.querySpec()
	_spec.Node.Columns = cdq.ctx.Fields
	if len(cdq.ctx.Fields) > 0 {
		_spec.Unique = cdq.ctx.Unique != nil && *cdq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, cdq.driver, _spec)
}

func (cdq *ChatDBQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(chatdb.Table, chatdb.Columns, sqlgraph.NewFieldSpec(chatdb.FieldID, field.TypeInt))
	_spec.From = cdq.sql
	if unique := cdq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if cdq.path != nil {
		_spec.Unique = true
	}
	if fields := cdq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, chatdb.FieldID)
		for i := range fields {
			if fields[i] != chatdb.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := cdq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := cdq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := cdq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := cdq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (cdq *ChatDBQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(cdq.driver.Dialect())
	t1 := builder.Table(chatdb.Table)
	columns := cdq.ctx.Fields
	if len(columns) == 0 {
		columns = chatdb.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if cdq.sql != nil {
		selector = cdq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if cdq.ctx.Unique != nil && *cdq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range cdq.predicates {
		p(selector)
	}
	for _, p := range cdq.order {
		p(selector)
	}
	if offset := cdq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := cdq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ChatDBGroupBy is the group-by builder for ChatDB entities.
type ChatDBGroupBy struct {
	selector
	build *ChatDBQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cdgb *ChatDBGroupBy) Aggregate(fns ...AggregateFunc) *ChatDBGroupBy {
	cdgb.fns = append(cdgb.fns, fns...)
	return cdgb
}

// Scan applies the selector query and scans the result into the given value.
func (cdgb *ChatDBGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cdgb.build.ctx, "GroupBy")
	if err := cdgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChatDBQuery, *ChatDBGroupBy](ctx, cdgb.build, cdgb, cdgb.build.inters, v)
}

func (cdgb *ChatDBGroupBy) sqlScan(ctx context.Context, root *ChatDBQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(cdgb.fns))
	for _, fn := range cdgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*cdgb.flds)+len(cdgb.fns))
		for _, f := range *cdgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*cdgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cdgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ChatDBSelect is the builder for selecting fields of ChatDB entities.
type ChatDBSelect struct {
	*ChatDBQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cds *ChatDBSelect) Aggregate(fns ...AggregateFunc) *ChatDBSelect {
	cds.fns = append(cds.fns, fns...)
	return cds
}

// Scan applies the selector query and scans the result into the given value.
func (cds *ChatDBSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cds.ctx, "Select")
	if err := cds.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChatDBQuery, *ChatDBSelect](ctx, cds.ChatDBQuery, cds, cds.inters, v)
}

func (cds *ChatDBSelect) sqlScan(ctx context.Context, root *ChatDBQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cds.fns))
	for _, fn := range cds.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cds.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cds.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
