// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/Axenos-dev/sse-openai-server/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/Axenos-dev/sse-openai-server/ent/chatdb"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// ChatDB is the client for interacting with the ChatDB builders.
	ChatDB *ChatDBClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.ChatDB = NewChatDBClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:    ctx,
		config: cfg,
		ChatDB: NewChatDBClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:    ctx,
		config: cfg,
		ChatDB: NewChatDBClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		ChatDB.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.ChatDB.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.ChatDB.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *ChatDBMutation:
		return c.ChatDB.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// ChatDBClient is a client for the ChatDB schema.
type ChatDBClient struct {
	config
}

// NewChatDBClient returns a client for the ChatDB from the given config.
func NewChatDBClient(c config) *ChatDBClient {
	return &ChatDBClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `chatdb.Hooks(f(g(h())))`.
func (c *ChatDBClient) Use(hooks ...Hook) {
	c.hooks.ChatDB = append(c.hooks.ChatDB, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `chatdb.Intercept(f(g(h())))`.
func (c *ChatDBClient) Intercept(interceptors ...Interceptor) {
	c.inters.ChatDB = append(c.inters.ChatDB, interceptors...)
}

// Create returns a builder for creating a ChatDB entity.
func (c *ChatDBClient) Create() *ChatDBCreate {
	mutation := newChatDBMutation(c.config, OpCreate)
	return &ChatDBCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ChatDB entities.
func (c *ChatDBClient) CreateBulk(builders ...*ChatDBCreate) *ChatDBCreateBulk {
	return &ChatDBCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ChatDBClient) MapCreateBulk(slice any, setFunc func(*ChatDBCreate, int)) *ChatDBCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ChatDBCreateBulk{err: fmt.Errorf("calling to ChatDBClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ChatDBCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ChatDBCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ChatDB.
func (c *ChatDBClient) Update() *ChatDBUpdate {
	mutation := newChatDBMutation(c.config, OpUpdate)
	return &ChatDBUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ChatDBClient) UpdateOne(cd *ChatDB) *ChatDBUpdateOne {
	mutation := newChatDBMutation(c.config, OpUpdateOne, withChatDB(cd))
	return &ChatDBUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ChatDBClient) UpdateOneID(id int) *ChatDBUpdateOne {
	mutation := newChatDBMutation(c.config, OpUpdateOne, withChatDBID(id))
	return &ChatDBUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ChatDB.
func (c *ChatDBClient) Delete() *ChatDBDelete {
	mutation := newChatDBMutation(c.config, OpDelete)
	return &ChatDBDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ChatDBClient) DeleteOne(cd *ChatDB) *ChatDBDeleteOne {
	return c.DeleteOneID(cd.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ChatDBClient) DeleteOneID(id int) *ChatDBDeleteOne {
	builder := c.Delete().Where(chatdb.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ChatDBDeleteOne{builder}
}

// Query returns a query builder for ChatDB.
func (c *ChatDBClient) Query() *ChatDBQuery {
	return &ChatDBQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeChatDB},
		inters: c.Interceptors(),
	}
}

// Get returns a ChatDB entity by its id.
func (c *ChatDBClient) Get(ctx context.Context, id int) (*ChatDB, error) {
	return c.Query().Where(chatdb.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ChatDBClient) GetX(ctx context.Context, id int) *ChatDB {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ChatDBClient) Hooks() []Hook {
	return c.hooks.ChatDB
}

// Interceptors returns the client interceptors.
func (c *ChatDBClient) Interceptors() []Interceptor {
	return c.inters.ChatDB
}

func (c *ChatDBClient) mutate(ctx context.Context, m *ChatDBMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ChatDBCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ChatDBUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ChatDBUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ChatDBDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ChatDB mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		ChatDB []ent.Hook
	}
	inters struct {
		ChatDB []ent.Interceptor
	}
)
