// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/Axenos-dev/sse-openai-server/ent/chatdb"
	"github.com/Axenos-dev/sse-openai-server/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	chatdbFields := schema.ChatDB{}.Fields()
	_ = chatdbFields
	// chatdbDescStatus is the schema descriptor for status field.
	chatdbDescStatus := chatdbFields[3].Descriptor()
	// chatdb.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	chatdb.StatusValidator = chatdbDescStatus.Validators[0].(func(int) error)
	// chatdbDescTimestamp is the schema descriptor for timestamp field.
	chatdbDescTimestamp := chatdbFields[4].Descriptor()
	// chatdb.DefaultTimestamp holds the default value on creation for the timestamp field.
	chatdb.DefaultTimestamp = chatdbDescTimestamp.Default.(func() int64)
}
